# environments/shared/04-hub/terraform.tfvars
org_prefix              = "YOUR_ORG_PREFIX"
location                = "australiaeast"
platform_subscription_id = "YOUR_PLATFORM_SUBSCRIPTION_ID"
hub_address_space       = "10.2.0.0/16"
nva_subnet_cidr         = "10.2.1.0/24"
gateway_subnet_cidr     = "10.2.0.64/27"
bastion_subnet_cidr     = "10.2.0.128/27"
management_subnet_cidr  = "10.2.2.0/24"
nat_gw_subnet_cidr      = "10.2.3.0/24"
router_vm_ip            = "10.2.1.4"
tfstate_rg_name        = "YOUR_ORG_PREFIX-tfstate-platform"
tfstate_sa_name         = "YOUR_TFSTATE_SA_NAME"
tfstate_container      = "tfstate"
# router_ssh_public_key — set in local.tfvars (gitignored) or GitHub Secret
# router_ssh_public_key = "ssh-ed25519 AAAA..."
